import { useMutation, useQuery, useQueryClient } from '@tanstack/vue-query'
import type { Ref } from 'vue'
import { useApi } from '@/lib/api'

/** Mirrors service-core's OrgResponse. external_id is null until the org is
 *  provisioned in the identity provider; `synced` is the derived flag. */
export interface Organization {
  id: string
  external_id: string | null
  synced: boolean
  slug: string
  name: string
  description: string
  created_at: string
  updated_at: string
}

export interface OrgListParams {
  page: number
  page_size: number
  q?: string
  sort_by?: string
  sort_dir?: 'asc' | 'desc'
}

export interface OrgListResponse {
  items: Organization[]
  total: number
}

export interface CreateOrgInput {
  name: string
  slug: string
  description: string
}

const KEY = 'organizations'

// The gateway namespaces backends as /<service>/v<major>/<path> under the API
// base URL (KrakenD endpoints generated by the registrator). service-core's spec
// is version v1.
const BASE = '/service-core/v1/admin/organizations'

export function useOrganizations(params: Ref<OrgListParams>) {
  const { request } = useApi()

  return useQuery({
    // params is reactive — vue-query refetches when it changes.
    queryKey: [KEY, params],
    queryFn: () => {
      const qs = new URLSearchParams()
      const p = params.value
      qs.set('page', String(p.page))
      qs.set('page_size', String(p.page_size))
      if (p.q) qs.set('q', p.q)
      if (p.sort_by) qs.set('sort_by', p.sort_by)
      if (p.sort_dir) qs.set('sort_dir', p.sort_dir)
      return request<OrgListResponse>(`${BASE}?${qs.toString()}`)
    },
    // Keep showing the previous page while the next loads — no flicker on paging.
    placeholderData: (prev) => prev,
  })
}

export function useCreateOrganization() {
  const { request } = useApi()
  const qc = useQueryClient()

  return useMutation({
    mutationFn: (input: CreateOrgInput) =>
      request<Organization>(BASE, {
        method: 'POST',
        body: JSON.stringify(input),
      }),
    onSuccess: () => qc.invalidateQueries({ queryKey: [KEY] }),
  })
}
