http:
  middlewares:
    oidc-auth:
      plugin:
        traefik-oidc-auth:
          Secret: "{{ env "OIDC_PLUGIN_SECRET" }}"
          Provider:
            Url: "{{ env "KC_PROTOCOL" }}://{{ env "KC_HOSTNAME" }}/realms/{{ env "APP_NAME" }}"
            ClientId: "{{ env "DEMO_REALM_CLIENT_ID" }}"
            ClientSecret: "{{ env "CLIENT_SECRET" }}"
            UsePkce: false
          Scopes: ["openid", "profile", "email"]
    oidc-auth-api:
      plugin:
        traefik-oidc-auth:
          Secret: "{{ env "OIDC_PLUGIN_SECRET" }}"
          Provider:
            Url: "{{ env "KC_PROTOCOL" }}://{{ env "KC_HOSTNAME" }}/realms/{{ env "APP_NAME" }}"
            ClientId: "{{ env "DEMO_REALM_CLIENT_ID" }}"
            ClientSecret: "{{ env "CLIENT_SECRET" }}"
            UsePkce: false
          UnauthorizedBehavior: Unauthorized
          BypassAuthenticationRule:  "PathRegexp(`.*/public/.*`)"
          Scopes: ["openid", "profile", "email"]
          Headers:
            - Name: 'Authorization'
              Value: "{{`Bearer {{ .accessToken }}`}}"