http:
  middlewares:
    oidc-auth:
      plugin:
        traefik-oidc-auth:
          Secret: "{{ env "OIDC_PLUGIN_SECRET" }}"
          Provider:
            Url: "http://keycloak.localhost/realms/dev-realm"
            ClientId: "fe"
            ClientSecret: "{{ env "CLIENT_SECRET" }}"
            UsePkce: false
          Scopes: ["openid", "profile", "email"]
    oidc-auth-api:
      plugin:
        traefik-oidc-auth:
          Secret: "{{ env "OIDC_PLUGIN_SECRET" }}"
          Provider:
            Url: "http://keycloak.localhost/realms/dev-realm"
            ClientId: "fe"
            ClientSecret: "{{ env "CLIENT_SECRET" }}"
            UsePkce: false
          UnauthorizedBehavior: Unauthorized
          Scopes: ["openid", "profile", "email"]
          Headers:
            - Name: 'Token'
              Value: "{{`Bearer {{ .accessToken }}`}}"
            - Name: 'X-User-Id'
              Value: "{{`{{ .claims.sub }}`}}"
            - Name: X-Acr
              Value: "{{`{{ .claims.acr }}`}}"
            - Name: X-Claims
              Value: "{{`{{ . }}`}}"
            - Name: X-Realm-Roles
              Value: "{{"{{range $i, $e := .claims.realm_access.roles}}{{if $i}},{{end}}{{$e}}{{end}}"}}"
            - Name: X-Client-Roles
              Value: "{{"{{range $i, $e := .claims.resource_access.fe.roles}}{{if $i}},{{end}}{{$e}}{{end}}"}}"