log:
  level: INFO

accesslog: true

experimental:
  abortOnPluginFailure: true
  plugins:
    traefik-oidc-auth:
      moduleName: 'github.com/sevensolutions/traefik-oidc-auth'
      version: 'v0.16.0'

# API and dashboard configuration
api:
  dashboard: true
  insecure: true

ping: {}

entryPoints:
  http:
    address: ':80'
    forwardedHeaders:
      insecure: true

providers:
  docker:
    endpoint: 'unix:///var/run/docker.sock'
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic-configuration.yml
